### PR TITLE
add initial description and pointer to external repo

### PR DESCRIPTION
**Pull request by R-Walmsley**

### CODE REVIEW

**Comment by R-Walmsley** [comment]
TO DO: if we amend external repo with file locations, point to relevant branch, not main. 

cc @ashreves

**Comment by R-Walmsley** [comment]
This branch is now ready for review - @aidanacquah could you check it? Obviously should be quick as most of the code is hosted externally.

**Review by angerhang — APPROVED** [review]
The site is looking ok now.

**Comment by R-Walmsley** [comment]
Thanks @angerhang !

**Pull request merged**
